### ISSUE TITLE
Thomas Media Center not showing favicon

### ISSUE THREAD

**Issue by varunsingh87** [shwin320/shwin320.github.io#2]
In Locker/Thomas Media Center.html, the favicon is linked locally to the owner, shwin320's, computer. This means that no one else is able to see that. The favicon.ico needs to be added to the github directory and linked relatively.

**Comment by shwin320** [comment]
The problem is fixed.

**Comment by varunsingh87** [comment]
Please refer the commit

**Comment by varunsingh87** [comment]
Resolved at https://github.com/shwin320/shwin320.github.io/commit/818aaaf3f6070c7fa9a9e067fc02f2fb2d301cb7
